AerolineaProject/AerolineaProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.inicio.urls')),
    path('',include('aplicaciones.empleados.urls')),
]

AerolineaProject/aplicaciones/empleados/urls.py
from django.urls import path
from . import views
app_name = 'empleados_app'

urlpatterns = [
    path('empleado/lista-empleados', views.lista_empleados, name = 'lista-empleados'),
    path('empleado/crear-empleado', views.CrearEmpleado.as_view(), name = 'crear-empleado'),
    path('empleado/modificar-empleado/<pk>/', views.ModificarEmpleado.as_view(), name = 'modificar-empleado'),
    path('empleado/eliminar-empleado/<pk>/', views.EliminarEmpleado.as_view(), name = 'eliminar-empleado'),
]

AerolineaProject/aplicaciones/inicio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('inicio/index', views.index),
    path('inicio/consultar-precios', views.consultar_precios),
    path('inicio/consultar-precios-js', views.consultar_precios_js),
    path('inicio/consultar-datos', views.consultar_datos),
    path('inicio/consultar-formulario', views.consultar_datos1),
]

AerolineaProject/aplicaciones/empleados/models.py
from django.db import models

# Create your models here.
class Empleado(models.Model):
    nombre = models.CharField('Nombre', max_length=60)
    correo = models.CharField('Correo',max_length=100)
    sueldo = models.DecimalField('Sueldo',max_digits=8, decimal_places=2)

    def __str__(self):
        return self.nombre + ' | ' +  self.correo + ' | ' + str(self.sueldo)

AerolineaProject/aplicaciones/inicio/models.py
from django.db import models

# Create your models here.

AerolineaProject/aplicaciones/empleados/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Empleado
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.

def lista_empleados(request):
    datos = {
        'lista' : Empleado.objects.all().order_by('nombre'),
        'titulo': 'Lista de empleados',
    }

    return render(request, 'empleados/lista-empleados2.html', datos)


class CrearEmpleado(CreateView):
    template_name='empleados/crear-empleado.html'
    model = Empleado
    fields = ['nombre', 'correo', 'sueldo']
    success_url = reverse_lazy('empleados_app:lista-empleados')

from django.contrib.messages.views import SuccessMessageMixin

class ModificarEmpleado(SuccessMessageMixin, UpdateView):
    template_name='empleados/modificar-empleado.html'
    model = Empleado
    fields = ['nombre', 'correo', 'sueldo']
    success_url = reverse_lazy('empleados_app:lista-empleados')
    success_message = "El registro '%(nombre)s' fue modificado exitosamente"

class EliminarEmpleado(SuccessMessageMixin, DeleteView):
    template_name = 'empleados/eliminar-empleado.html'
    model= Empleado
    success_url = reverse_lazy('empleados_app:lista-empleados')
    success_message = "El registro fue elimnado exitosamente"

AerolineaProject/aplicaciones/inicio/views.py
from django.shortcuts import render
import requests 

# Create your views here.

def index(request):
    return render(request, 'inicio/index.html')

def consultar_precios(request):
    pagina = 1
    if request.GET:
        pagina = int(request.GET['page'])

    url_binance='https://api.binance.com/api/v3/ticker/price'
    datos = requests.get(url_binance)

    contexto = {'precios': datos.json()[pagina*10-10:pagina*10:]}

    return render(request, 'inicio/consultar-precios.html', contexto)

def consultar_precios_js(request):
    return render(request, 'inicio/consultar-precios-js.html')


def consultar_datos(request):
    url_datos='https://jsonplaceholder.typicode.com/users'
    datos1 = requests.get(url_datos)

    contexto1 = {'datos': datos1.json()}

    return render(request, 'inicio/consultar-datos.html', contexto1)

def consultar_datos1(request):
    url_datos='https://jsonplaceholder.typicode.com/posts/1'
    datos2 = requests.get(url_datos)

    contexto2 = {'formulario': datos2.json()}

    return render(request, 'inicio/consultar-formulario.html', contexto2)

AerolineaProject/templates/empleados/crear-empleado.html
{% extends 'layout/base_bootstrap.html' %}


{% block titulo %}
    Nuevo empleado
{% endblock titulo %}

{% load bootstrap5 %}

{% block content %}
    <h1>Nuevo Empleado</h1>

    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form  %}
            <!-- <table>
            {{ form.as_table }}
            </table> -->
        <input type="submit" value="Guardar" class="btn btn-primary">
    </form>
{% endblock content %}
    
    

AerolineaProject/templates/empleados/eliminar-empleado.html
{% extends 'layout/base_bootstrap.html' %}


{% block titulo %}
    Eliminar Empleado
{% endblock titulo %}

{% load bootstrap5 %}


{% block content %}
<h1>Eliminar Empleado</h1>

<form action="" method="POST">
    {% csrf_token %}
    Desea eliminar el registro seleccionado?
    <input type="submit" value="Si" class="btn btn-primary">
    <a href="{% url 'empleados_app:lista-empleados' %}" class="btn btn-secondary">Cancelar</a>
</form>
    
{% endblock content %}
    
    

AerolineaProject/templates/empleados/lista-empleados.html
{% extends 'layout/base.html' %}


{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
    

{% block content %}

<h1>{{ titulo }}</h1>

<a href="">Nuevo Empleado</a>
<table>
    <thead><tr><th>ID</th><th>Nombre</th><th>Correo</th><th>Sueldo</th></tr></thead>
    <tbody>
        {% for e in lista %}
            <tr>
                <td>{{ e.id }}</td>
                <td>{{ e.nombre }}</td>
                <td>{{ e.correo }}</td>
                <td>{{ e.sueldo }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
    
{% endblock content %}
    

AerolineaProject/templates/empleados/lista-empleados2.html
{% extends 'layout/base_bootstrap.html' %}


{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
    

{% block content %}

<h1>{{ titulo }}</h1>

<a href="{% url 'empleados_app:crear-empleado' %}" class="btn btn-primary">Nuevo Empleado</a><br><br>

{% if messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {% for message in messages %}
        <strong>Mensaje: </strong> {{ message }}
        {% endfor %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endif %}


<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nombre</th>
            <th scope="col">Correo</th>
            <th scope="col">Sueldo</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for e in lista %}
            <tr>
                <td>{{ e.id }}</td>
                <td>{{ e.nombre }}</td>
                <td>{{ e.correo }}</td>
                <td>{{ e.sueldo }}</td>
                <td>
                    <a href="{% url 'empleados_app:eliminar-empleado' e.id %}"><i class="fa-solid fa-trash"></i></a> &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;
                    <a href="{% url 'empleados_app:modificar-empleado' e.id %}"><i class="fa-solid fa-pen-to-square"></i></a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
    
{% endblock content %}
    

AerolineaProject/templates/empleados/modificar-empleado.html
{% extends 'layout/base_bootstrap.html' %}


{% block titulo %}
    Modificar Empleado
{% endblock titulo %}

{% load bootstrap5 %}


{% block content %}
<h1>Modificar Empleado</h1>

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" value="Actualizar" class="btn btn-primary">
</form>
    
{% endblock content %}
    
    

AerolineaProject/templates/inicio/consultar-datos.html
{% extends 'layout/base_bootstrap.html'%}


{% block titulo %}
    Datos
{% endblock titulo %}
    

{% block content %}
    <h1>Datos</h1>
    <table class="table table-striped table-hover">
        <thead>
            <tr><th>ID</th><th>NAME</th><th>USERNAME</th><th>EMAIL</th><th>PHONE</th></tr>
        </thead>
        <tbody>
            {% for  dat in datos %}
                <tr><td>{{ dat.id}}</td><td>{{ dat.name }}</td><td>{{ dat.username }}</td><td> {{ dat.email }}</td><td>{{ dat.phone }}</td></tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

AerolineaProject/templates/inicio/consultar-formulario.html
{% extends 'layout/base_bootstrap.html'%}


{% block titulo %}
    Datos
{% endblock titulo %}
    

{% block content %}
    <h1>Formulario</h1>
    

    <form>
        <div>
            <label>UserID:</label>
            <input class="form-control"type="text" name="text" value="{{ formulario.userId }}">
        </div>
        <div>
            <label>ID:</label>
            <input class="form-control"type="text" name="text" value="{{ formulario.id }}">
        </div>
        <div>
            <label>Titulo:</label>
            <textarea class="form-control" name="text" >{{ formulario.title }}</textarea>
        </div>
        <div>
            <label>Body:</label>
            <textarea class="form-control" name="text" cols="30" rows="6">{{ formulario.body }}</textarea>
        </div>

    </form>
{% endblock content %}

AerolineaProject/templates/inicio/consultar-precios-js.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consumo API</title>
</head>
<body>

    <div id="contenido">

    </div>

    <script>
        var requestOptions = {
            method: 'GET',
            redirect: 'follow'
        };

        fetch("https://api.binance.com/api/v3/ticker/price", requestOptions)
            .then(response => response.text())
            .then(result => {
                document.getElementById('contenido').innerHTML = result
                console.log(result)
            
            })
            .catch(error => console.log('error', error));
    </script>
    
</body>
</html>

AerolineaProject/templates/inicio/consultar-precios.html
{% extends 'layout/base_bootstrap.html'%}


{% block titulo %}
    Crypto prices
{% endblock titulo %}
    

{% block content %}
    <h1>Crypto prices</h1>
    <table class="table table-striped table-hover">
        <thead>
            <tr><th>Symbol</th><th>Price</th></tr>
        </thead>
        <tbody>
            {% for  crypto in precios %}
                <tr><td>{{ crypto.symbol}}</td><td>{{ crypto.price }}</td></tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}
    

AerolineaProject/templates/inicio/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de bienvenida</title>
</head>
<body>

    <h1>Hola desde la app de Inicio</h1>
    

</body>
</html>

AerolineaProject/templates/layout/_footer.html
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="bootstrap" viewBox="0 0 118 94">
        <title>Bootstrap</title>
        <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
    </symbol>
    </svg>
    <div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-muted">&copy; 2022 Company, Inc</p>
    
        <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        </a>
    
        <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
        </ul>
        </footer>
      </div>

AerolineaProject/templates/layout/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">AerolineaProject</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'empleados_app:lista-empleados' %}">Empleados</a>
          </li>
          
          
        </ul>

        <ul class="navbar-nav ">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Alicia Lopez [alicia123]
                </a>
                <ul class="dropdown-menu dropdown-menu-start">
                  <li><a class="dropdown-item" href="#">Perfil</a></li>
                  <li><a class="dropdown-item" href="#">Cambiar Contraseña</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Cerrar Sesion</a></li>
                </ul>
              </li>
        </ul>
        
      </div>
    </div>
  </nav>






  <div class="form-group row mb-4">
    <div class="col-sm-2">

    </div>
    <div class="col-sm-2">

    </div>
  </div>

AerolineaProject/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}{% endblock %} - Aerolinea </title>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
</head>
<body>

    <header class="top">
        <nav>
            <a href="">Inicio</a>
            <a href="" class="active">Contacto</a>
            <a href="">A cerca de</a>
        </nav>
    </header>

    <main>
        <div>
            
            {% block content %}{% endblock %}
                
        </div>
    </main>

    <footer>
        <p>&copy; Copyright 2023</p>
    </footer>
    
</body>
</html>

AerolineaProject/templates/layout/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}{% endblock %} - Aerolinea </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
</head>
<body>

    <header class="top">
       {% include 'layout/_navbar.html' %}
    </header>

    <main>
        <div class="content container">
            
            {% block content %}{% endblock %}
                
        </div>
    </main>
        {% include 'layout/_footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>